environments:
  development:
  staging:

---

repositories:
  - name: xjdao2025
    url: oci://ghcr.io/xjdao2025/charts
    oci: true

helmDefaults:
  wait: true
  timeout: 600

releases:
  - name: social-app
    namespace: xjdao2025
    chart: xjdao2025/social-app
    version: {{ requiredEnv "VERSION_NUMBER" }}
    values:
      - ./values/{{ .Environment.Name }}.yaml